Repository MicrosoftDocs/cpp-docs.es-es, pull requests merged in 2019-02, with the labels that each got.

#12 Correción en la redacción
  docs/windows/universal-windows-apps-cpp.md
Labels: Linguistic Suggestion, Partially accepted

#15 Cambio de palabra
  docs/cppcx/visual-c-language-reference-c-cx.md
Labels: Accepted, Linguistic Suggestion

#24 Corrección en la traducción
  docs/windows/resource-files-visual-studio.md
Labels: Linguistic Suggestion, Partially accepted

#22 Mala traducción
  docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md
Labels: Linguistic Suggestion, Partially accepted

#23 Error en la traducción
  docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md
Labels: Accepted, Linguistic Suggestion

#21 Mala traducción
  docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md
Labels: Linguistic Suggestion, Partially accepted

#20 Mala traducción
  docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md
Labels: Accepted, Linguistic Suggestion

#18 Error gramatical
  docs/windows/desktop-applications-visual-cpp.md
Labels: Accepted, Linguistic Suggestion

#17 Error de redacción
  docs/windows/desktop-applications-visual-cpp.md
Labels: Partially accepted
